### ISSUE TITLE
Some issues with some of the external roles

### ISSUE THREAD

**Issue by giovannipizzi** [marvel-nccr/ansible-playbook-workhorse#2]
For the Ljubljana 2019 tutorial, I had issues with the `marvel-nncr.cp2k` and `marvel-nccr.aiidalab` roles. Since I didn't need them in the VM, I just commented them out in the playbook, but probably this needs investigation to know what has changed and why they give an error (that I don't have anymore with me, but by just rerunning ansible they should show up).

**Comment by ltalirz** [comment]
Sorry, did you take the `xiamen2019` branch here or the `master` branch?

`xiamen2019` included a number of updates - I thought I had pushed them into `master` already but it turns out I only had them in a local `develop` branch.

I've merged the relevant changes back into `master` now.
I also tested the `cp2k` role which seemed to work fine.
Happy to reopen in case problems persist.

**Comment by giovannipizzi** [comment]
Most probably, `develop`, so ok thanks!
